Algoritmo "divisao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/05/2022
Var
// Seção de Declarações das variáveis
      n1, n2, divisao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
     leia (n1, n2)
     divisao<-n1 / n2
     escreva(divisao)

Fimalgoritmo