Algoritmo "Multiplicacao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jesus Germano da Silva junior
// Descrição   : multiplicação de dois números
// Autor(a)    : Jesus Germano da Silva junior
// Data atual  : 15/05/2022
Var
// Seção de Declarações das variáveis 
      n1, n2, multiplicacao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     leia (n1, n2)
     multiplicacao<-n1 * n2
     escreva(multiplicacao)

Fimalgoritmo