Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jesus Germano da Silva Junior
// Descrição   : Soma de numeros
// Autor(a)    : Jesus Germano da Silva Junior
// Data atual  : 14/05/2022
Var
// Seção de Declarações das variáveis 
     n1, n2, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Leia (n1, n2)
     soma<-n1 + n2
     Escreva(soma)

Fimalgoritmo