Algoritmo "subtracao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/05/2022
Var
// Seção de Declarações das variáveis
     n1, n2, subtracao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
     Leia (n1, n2)
     subtracao<-n1 - n2
     Escreva(subtracao)

Fimalgoritmo